# TODO
# general settings
name: train_ConStyleMaximDenoise
model_type: ConStyle
manual_seed: 10

num_gpu: 1
gpu_id: 0

datasets:
  train:
    name: DFWB
    type: Dataset_Maxim_GaussianDenoising
    sigma_type: constant
    sigma_range: 25
    in_ch: 3
    dataroot_gt: path for 'DFWB'
    dataroot_lq: none
    filename_tmpl: '{}'
    pin_memory: True
    io_backend:
      type: lmdb

    scale: 1
    gt_size: 128
    use_hflip: True
    use_rot: True
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda

  val:
    name: CBSD68_part
    type: Dataset_Maxim_GaussianDenoising
    sigma_test: 25
    in_ch: 3
    dataroot_gt: path for 'CBSD68_part'
    dataroot_lq: none
    filename_tmpl: '{}'
    io_backend:
      type: disk

network_g:
  type: ConStyleMaxim

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  total_iter: 703632
  ConStyle_iter: 999999
  warmup_iter: -1
  ema_decay: 0.999

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [ 0.9, 0.999 ]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [243312, 460320]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  CrossEntropy_opt:
    type: CrossEntropyLoss

  content_opt:
    type: ContentLoss

  style_opt:
    type: StyleLoss

val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr_y:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: True

    psnr_rgb:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: False

logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: False
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
